title: Fleximo Docs
description: Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

color_scheme: dark
mermaid:
  version: "9.1.3"
